# Config file for automatic testing at travis-ci.org

language: python

python:
#  - "3.4"
#  - "3.3"
  - "3.2"
  - "2.7"
#  - "2.6"
#  - "pypy"

virtualenv:
  system_site_packages: true

#install BerkeleyDB deps
before_install:
  - sudo apt-get update -qq
#- sudo apt-get install -y libdb-dev
#  - sudo apt-get install `apt-cache depends pkgname | awk '/Depends:/{print$2}'`
  - sudo apt-get install python-bsddb3 python3-bsddb3

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
